/**
 * 系统设置键常量
 * 与 anheyu-app 后端 Go 定义保持同步
 */

// ==================== 站点基础配置 ====================
export const KEY_APP_NAME = "APP_NAME";
export const KEY_SUB_TITLE = "SUB_TITLE";
export const KEY_SITE_DESCRIPTION = "SITE_DESCRIPTION";
export const KEY_SITE_KEYWORDS = "SITE_KEYWORDS";
export const KEY_SITE_URL = "SITE_URL";
export const KEY_SITE_ANNOUNCEMENT = "SITE_ANNOUNCEMENT";
export const KEY_ICP_NUMBER = "ICP_NUMBER";
export const KEY_POLICE_RECORD_NUMBER = "POLICE_RECORD_NUMBER";
export const KEY_POLICE_RECORD_ICON = "POLICE_RECORD_ICON";
export const KEY_ENABLE_REGISTRATION = "ENABLE_REGISTRATION";
export const KEY_DEFAULT_THEME_MODE = "DEFAULT_THEME_MODE";
export const KEY_APPEARANCE_SKIN = "APPEARANCE_SKIN";
export const KEY_APPEARANCE_TOKENS = "APPEARANCE_TOKENS";
export const KEY_ABOUT_LINK = "ABOUT_LINK";
export const KEY_DEFAULT_THUMB_PARAM = "DEFAULT_THUMB_PARAM";
export const KEY_DEFAULT_BIG_PARAM = "DEFAULT_BIG_PARAM";

// ==================== Logo 与图标 ====================
export const KEY_LOGO_HORIZONTAL_DAY = "LOGO_HORIZONTAL_DAY";
export const KEY_LOGO_HORIZONTAL_NIGHT = "LOGO_HORIZONTAL_NIGHT";
export const KEY_ICON_URL = "ICON_URL";
export const KEY_LOGO_URL_192 = "LOGO_URL_192x192";
export const KEY_LOGO_URL_512 = "LOGO_URL_512x512";
export const KEY_LOGO_URL = "LOGO_URL";
export const KEY_GRAVATAR_URL = "GRAVATAR_URL";
export const KEY_DEFAULT_GRAVATAR_TYPE = "DEFAULT_GRAVATAR_TYPE";
export const KEY_USER_AVATAR = "USER_AVATAR";

// ==================== Header/Nav 配置 ====================
export const KEY_HEADER_MENU = "header.menu";
export const KEY_HEADER_NAV_TRAVELLING = "header.nav.travelling";
export const KEY_HEADER_NAV_CLOCK = "header.nav.clock";
export const KEY_HEADER_NAV_MENU = "header.nav.menu";
export const KEY_USERPANEL_SHOW_USER_CENTER = "userpanel.show_user_center";
export const KEY_USERPANEL_SHOW_NOTIFICATIONS = "userpanel.show_notifications";
export const KEY_USERPANEL_SHOW_PUBLISH_ARTICLE = "userpanel.show_publish_article";
export const KEY_USERPANEL_SHOW_ADMIN_DASHBOARD = "userpanel.show_admin_dashboard";
export const KEY_HOME_TOP = "HOME_TOP";
export const KEY_CREATIVITY = "CREATIVITY";

// ==================== 前台配置 ====================
export const KEY_FRONT_DESK_SITE_OWNER_NAME = "frontDesk.siteOwner.name";
export const KEY_FRONT_DESK_SITE_OWNER_EMAIL = "frontDesk.siteOwner.email";

// ==================== Footer 配置 ====================
export const KEY_FOOTER_OWNER_NAME = "footer.owner.name";
export const KEY_FOOTER_OWNER_SINCE = "footer.owner.since";
export const KEY_FOOTER_CUSTOM_TEXT = "footer.custom_text";
export const KEY_FOOTER_RUNTIME_ENABLE = "footer.runtime.enable";
export const KEY_FOOTER_RUNTIME_LAUNCH_TIME = "footer.runtime.launch_time";
export const KEY_FOOTER_RUNTIME_WORK_IMG = "footer.runtime.work_img";
export const KEY_FOOTER_RUNTIME_WORK_DESC = "footer.runtime.work_description";
export const KEY_FOOTER_RUNTIME_OFFDUTY_IMG = "footer.runtime.offduty_img";
export const KEY_FOOTER_RUNTIME_OFFDUTY_DESC = "footer.runtime.offduty_description";
export const KEY_FOOTER_SOCIALBAR_CENTER_IMG = "footer.socialBar.centerImg";
export const KEY_FOOTER_LIST_RANDOM_FRIENDS = "footer.list.randomFriends";
export const KEY_FOOTER_BAR_AUTHOR_LINK = "footer.bar.authorLink";
export const KEY_FOOTER_BAR_CC_LINK = "footer.bar.cc.link";
export const KEY_FOOTER_BADGE_ENABLE = "footer.badge.enable";
export const KEY_FOOTER_BADGE_LIST = "footer.badge.list";
export const KEY_FOOTER_SOCIALBAR_LEFT = "footer.socialBar.left";
export const KEY_FOOTER_SOCIALBAR_RIGHT = "footer.socialBar.right";
export const KEY_FOOTER_PROJECT_LIST = "footer.project.list";
export const KEY_FOOTER_BAR_LINK_LIST = "footer.bar.linkList";
export const KEY_FOOTER_UPTIME_KUMA_ENABLE = "footer.uptime_kuma.enable";
export const KEY_FOOTER_UPTIME_KUMA_PAGE_URL = "footer.uptime_kuma.page_url";

// ==================== 侧边栏配置 ====================
export const KEY_SIDEBAR_AUTHOR_ENABLE = "sidebar.author.enable";
export const KEY_SIDEBAR_AUTHOR_DESCRIPTION = "sidebar.author.description";
export const KEY_SIDEBAR_AUTHOR_STATUS_IMG = "sidebar.author.statusImg";
export const KEY_SIDEBAR_AUTHOR_SKILLS = "sidebar.author.skills";
export const KEY_SIDEBAR_AUTHOR_SOCIAL = "sidebar.author.social";
export const KEY_SIDEBAR_WECHAT_ENABLE = "sidebar.wechat.enable";
export const KEY_SIDEBAR_WECHAT_FACE = "sidebar.wechat.face";
export const KEY_SIDEBAR_WECHAT_BACK_FACE = "sidebar.wechat.backFace";
export const KEY_SIDEBAR_WECHAT_BLUR_BG = "sidebar.wechat.blurBackground";
export const KEY_SIDEBAR_WECHAT_LINK = "sidebar.wechat.link";
export const KEY_SIDEBAR_TAGS_ENABLE = "sidebar.tags.enable";
export const KEY_SIDEBAR_TAGS_HIGHLIGHT = "sidebar.tags.highlight";
export const KEY_SIDEBAR_SITEINFO_POST_COUNT = "sidebar.siteinfo.totalPostCount";
export const KEY_SIDEBAR_SITEINFO_RUNTIME = "sidebar.siteinfo.runtimeEnable";
export const KEY_SIDEBAR_SITEINFO_WORD_COUNT = "sidebar.siteinfo.totalWordCount";
export const KEY_SIDEBAR_ARCHIVE_MONTHS = "sidebar.archive.displayMonths";
export const KEY_SIDEBAR_CUSTOM_SHOW_IN_POST = "sidebar.custom.showInPost";
export const KEY_SIDEBAR_TOC_COLLAPSE_MODE = "sidebar.toc.collapseMode";
export const KEY_SIDEBAR_SERIES_POST_COUNT = "sidebar.series.postCount";
export const KEY_SIDEBAR_RECENT_POST_ENABLE = "sidebar.recentPost.enable";
export const KEY_SIDEBAR_RECENT_POST_COUNT = "sidebar.recentPost.count";
export const KEY_SIDEBAR_DOC_LINKS = "sidebar.doc.links";
export const KEY_CUSTOM_SIDEBAR = "CUSTOM_SIDEBAR";

// ==================== 天气组件配置 ====================
export const KEY_WEATHER_ENABLE = "sidebar.weather.enable";
export const KEY_WEATHER_ENABLE_PAGE = "sidebar.weather.enable_page";
export const KEY_WEATHER_QWEATHER_KEY = "sidebar.weather.qweather_key";
export const KEY_WEATHER_QWEATHER_API_HOST = "sidebar.weather.qweather_api_host";
export const KEY_WEATHER_IP_API_KEY = "sidebar.weather.ip_api_key";
export const KEY_WEATHER_LOADING = "sidebar.weather.loading";
export const KEY_WEATHER_DEFAULT_RECT = "sidebar.weather.default_rectangle";
export const KEY_WEATHER_RECTANGLE = "sidebar.weather.rectangle";

// ==================== 页面样式 ====================
export const KEY_ENABLE_EXTERNAL_LINK_WARNING = "ENABLE_EXTERNAL_LINK_WARNING";
export const KEY_DISABLE_RIGHT_MENU = "DISABLE_RIGHT_MENU";
export const KEY_RESPECT_REDUCED_MOTION = "RESPECT_REDUCED_MOTION";
export const KEY_CUSTOM_HEADER_HTML = "CUSTOM_HEADER_HTML";
export const KEY_CUSTOM_FOOTER_HTML = "CUSTOM_FOOTER_HTML";
export const KEY_CUSTOM_CSS = "CUSTOM_CSS";
export const KEY_CUSTOM_JS = "CUSTOM_JS";
export const KEY_CUSTOM_POST_TOP_HTML = "CUSTOM_POST_TOP_HTML";
export const KEY_CUSTOM_POST_BOTTOM_HTML = "CUSTOM_POST_BOTTOM_HTML";
export const KEY_PAGE_ONE_IMAGE_CONFIG = "page.one_image.config";
export const KEY_HITOKOTO_API = "page.one_image.hitokoto_api";
export const KEY_TYPING_SPEED = "page.one_image.typing_speed";

// ==================== 文章配置 ====================
export const KEY_POST_DEFAULT_COVER = "post.default.cover";
export const KEY_POST_EXPIRATION_TIME = "post.expiration_time";
export const KEY_POST_DOUBLE_COLUMN = "post.default.double_column";
export const KEY_POST_PAGE_SIZE = "post.default.page_size";
export const KEY_POST_ENABLE_PRIMARY_COLOR = "post.default.enable_primary_color_tag";
export const KEY_POST_404_IMAGE = "post.page404.default_image";
export const KEY_POST_REWARD_ENABLE = "post.reward.enable";
export const KEY_POST_REWARD_WECHAT_QR = "post.reward.wechat_qr";
export const KEY_POST_REWARD_ALIPAY_QR = "post.reward.alipay_qr";
export const KEY_POST_REWARD_WECHAT_ENABLE = "post.reward.wechat_enable";
export const KEY_POST_REWARD_ALIPAY_ENABLE = "post.reward.alipay_enable";
export const KEY_POST_REWARD_BUTTON_TEXT = "post.reward.button_text";
export const KEY_POST_REWARD_TITLE = "post.reward.title";
export const KEY_POST_REWARD_WECHAT_LABEL = "post.reward.wechat_label";
export const KEY_POST_REWARD_ALIPAY_LABEL = "post.reward.alipay_label";
export const KEY_POST_REWARD_LIST_BTN_TEXT = "post.reward.list_button_text";
export const KEY_POST_REWARD_LIST_BTN_DESC = "post.reward.list_button_desc";
export const KEY_POST_CODE_MAX_LINES = "post.code_block.code_max_lines";
export const KEY_POST_CODE_MAC_STYLE = "post.code_block.mac_style";
export const KEY_POST_COPY_ENABLE = "post.copy.enable";
export const KEY_POST_COPY_COPYRIGHT_ENABLE = "post.copy.copyright_enable";
export const KEY_POST_COPY_COPYRIGHT_ORIGINAL = "post.copy.copyright_original";
export const KEY_POST_COPY_COPYRIGHT_REPRINT = "post.copy.copyright_reprint";
export const KEY_POST_TOC_HASH_MODE = "post.toc.hash_update_mode";
export const KEY_POST_WAVES_ENABLE = "post.waves.enable";
export const KEY_POST_COPYRIGHT_ORIGINAL = "post.copyright.original_template";
export const KEY_POST_COPYRIGHT_REPRINT_WITH_URL = "post.copyright.reprint_template_with_url";
export const KEY_POST_COPYRIGHT_REPRINT_NO_URL = "post.copyright.reprint_template_without_url";
export const KEY_POST_SHOW_REWARD_BTN = "post.copyright.show_reward_button";
export const KEY_POST_SHOW_SHARE_BTN = "post.copyright.show_share_button";
export const KEY_POST_SHOW_SUBSCRIBE_BTN = "post.copyright.show_subscribe_button";
export const KEY_POST_SUBSCRIBE_ENABLE = "post.subscribe.enable";
export const KEY_POST_SUBSCRIBE_BTN_TEXT = "post.subscribe.button_text";
export const KEY_POST_SUBSCRIBE_TITLE = "post.subscribe.dialog_title";
export const KEY_POST_SUBSCRIBE_DESC = "post.subscribe.dialog_desc";
export const KEY_POST_SUBSCRIBE_MAIL_SUBJECT = "post.subscribe.mail_subject";
export const KEY_POST_SUBSCRIBE_MAIL_TEMPLATE = "post.subscribe.mail_template";

// ==================== CDN 配置 ====================
export const KEY_CDN_ENABLE = "cdn.enable";
export const KEY_CDN_PROVIDER = "cdn.provider";
export const KEY_CDN_SECRET_ID = "cdn.secret_id";
export const KEY_CDN_SECRET_KEY = "cdn.secret_key";
export const KEY_CDN_REGION = "cdn.region";
export const KEY_CDN_DOMAIN = "cdn.domain";
export const KEY_CDN_ZONE_ID = "cdn.zone_id";
export const KEY_CDN_BASE_URL = "cdn.base_url";

// ==================== 多人共创配置 (PRO) ====================
export const KEY_MULTI_AUTHOR_ENABLE = "article.multi_author.enable";
export const KEY_MULTI_AUTHOR_NEED_REVIEW = "article.multi_author.need_review";
export const KEY_ARTICLE_REVIEW_NOTIFY_ENABLE = "article.review.notify.enable";
export const KEY_ARTICLE_REVIEW_NOTIFY_EMAIL = "article.review.notify.email";
export const KEY_ARTICLE_REVIEW_NOTIFY_PUSH = "article.review.notify.push";
export const KEY_ARTICLE_REVIEW_PUSH_CHANNEL = "article.review.pushoo.channel";
export const KEY_ARTICLE_REVIEW_PUSH_URL = "article.review.pushoo.url";
export const KEY_ARTICLE_REVIEW_WEBHOOK_BODY = "article.review.webhook.request_body";
export const KEY_ARTICLE_REVIEW_WEBHOOK_HEADERS = "article.review.webhook.headers";
export const KEY_ARTICLE_REVIEW_MAIL_SUBJECT_APPROVED = "article.review.mail_subject_approved";
export const KEY_ARTICLE_REVIEW_MAIL_TEMPLATE_APPROVED = "article.review.mail_template_approved";
export const KEY_ARTICLE_REVIEW_MAIL_SUBJECT_REJECTED = "article.review.mail_subject_rejected";
export const KEY_ARTICLE_REVIEW_MAIL_TEMPLATE_REJECTED = "article.review.mail_template_rejected";

// ==================== 文件处理配置 ====================
export const KEY_UPLOAD_ALLOWED_EXTENSIONS = "UPLOAD_ALLOWED_EXTENSIONS";
export const KEY_UPLOAD_DENIED_EXTENSIONS = "UPLOAD_DENIED_EXTENSIONS";
export const KEY_ENABLE_VIPS_GENERATOR = "ENABLE_VIPS_GENERATOR";
export const KEY_VIPS_PATH = "VIPS_PATH";
export const KEY_VIPS_MAX_FILE_SIZE = "VIPS_MAX_FILE_SIZE";
export const KEY_VIPS_SUPPORTED_EXTS = "VIPS_SUPPORTED_EXTS";
export const KEY_ENABLE_MUSIC_COVER_GENERATOR = "ENABLE_MUSIC_COVER_GENERATOR";
export const KEY_MUSIC_COVER_MAX_FILE_SIZE = "MUSIC_COVER_MAX_FILE_SIZE";
export const KEY_MUSIC_COVER_SUPPORTED_EXTS = "MUSIC_COVER_SUPPORTED_EXTS";
export const KEY_ENABLE_FFMPEG_GENERATOR = "ENABLE_FFMPEG_GENERATOR";
export const KEY_FFMPEG_PATH = "FFMPEG_PATH";
export const KEY_FFMPEG_MAX_FILE_SIZE = "FFMPEG_MAX_FILE_SIZE";
export const KEY_FFMPEG_SUPPORTED_EXTS = "FFMPEG_SUPPORTED_EXTS";
export const KEY_FFMPEG_CAPTURE_TIME = "FFMPEG_CAPTURE_TIME";
export const KEY_ENABLE_LIBRAW_GENERATOR = "ENABLE_LIBRAW_GENERATOR";
export const KEY_LIBRAW_PATH = "LIBRAW_PATH";
export const KEY_LIBRAW_MAX_FILE_SIZE = "LIBRAW_MAX_FILE_SIZE";
export const KEY_LIBRAW_SUPPORTED_EXTS = "LIBRAW_SUPPORTED_EXTS";
export const KEY_ENABLE_BUILTIN_GENERATOR = "ENABLE_BUILTIN_GENERATOR";
export const KEY_BUILTIN_MAX_FILE_SIZE = "BUILTIN_MAX_FILE_SIZE";
export const KEY_BUILTIN_DIRECT_SERVE_EXTS = "BUILTIN_DIRECT_SERVE_EXTS";
export const KEY_QUEUE_THUMB_CONCURRENCY = "QUEUE_THUMB_CONCURRENCY";
export const KEY_QUEUE_THUMB_MAX_EXEC_TIME = "QUEUE_THUMB_MAX_EXEC_TIME";
export const KEY_QUEUE_THUMB_BACKOFF_FACTOR = "QUEUE_THUMB_BACKOFF_FACTOR";
export const KEY_QUEUE_THUMB_MAX_BACKOFF = "QUEUE_THUMB_MAX_BACKOFF";
export const KEY_QUEUE_THUMB_MAX_RETRIES = "QUEUE_THUMB_MAX_RETRIES";
export const KEY_QUEUE_THUMB_RETRY_DELAY = "QUEUE_THUMB_RETRY_DELAY";
export const KEY_ENABLE_EXIF_EXTRACTOR = "ENABLE_EXIF_EXTRACTOR";
export const KEY_EXIF_MAX_SIZE_LOCAL = "EXIF_MAX_SIZE_LOCAL";
export const KEY_EXIF_MAX_SIZE_REMOTE = "EXIF_MAX_SIZE_REMOTE";
export const KEY_EXIF_USE_BRUTE_FORCE = "EXIF_USE_BRUTE_FORCE";
export const KEY_ENABLE_MUSIC_EXTRACTOR = "ENABLE_MUSIC_EXTRACTOR";
export const KEY_MUSIC_MAX_SIZE_LOCAL = "MUSIC_MAX_SIZE_LOCAL";
export const KEY_MUSIC_MAX_SIZE_REMOTE = "MUSIC_MAX_SIZE_REMOTE";

// ==================== 评论配置 ====================
export const KEY_COMMENT_ENABLE = "comment.enable";
export const KEY_COMMENT_BARRAGE_ENABLE = "comment.barrage_enable";
export const KEY_COMMENT_LOGIN_REQUIRED = "comment.login_required";
export const KEY_COMMENT_PAGE_SIZE = "comment.page_size";
export const KEY_COMMENT_MASTER_TAG = "comment.master_tag";
export const KEY_COMMENT_PLACEHOLDER = "comment.placeholder";
export const KEY_COMMENT_EMOJI_CDN = "comment.emoji_cdn";
export const KEY_COMMENT_BLOGGER_EMAIL = "comment.blogger_email";
export const KEY_COMMENT_ANONYMOUS_EMAIL = "comment.anonymous_email";
export const KEY_COMMENT_SHOW_UA = "comment.show_ua";
export const KEY_COMMENT_SHOW_REGION = "comment.show_region";
export const KEY_COMMENT_ALLOW_IMAGE_UPLOAD = "comment.allow_image_upload";
export const KEY_COMMENT_LIMIT_PER_MINUTE = "comment.limit_per_minute";
export const KEY_COMMENT_LIMIT_LENGTH = "comment.limit_length";
export const KEY_COMMENT_FORBIDDEN_WORDS = "comment.forbidden_words";
export const KEY_COMMENT_AI_DETECT_ENABLE = "comment.ai_detect_enable";
export const KEY_COMMENT_AI_DETECT_API_URL = "comment.ai_detect_api_url";
export const KEY_COMMENT_AI_DETECT_ACTION = "comment.ai_detect_action";
export const KEY_COMMENT_AI_DETECT_RISK_LEVEL = "comment.ai_detect_risk_level";
export const KEY_COMMENT_QQ_API_URL = "comment.qq_api_url";
export const KEY_COMMENT_QQ_API_KEY = "comment.qq_api_key";
export const KEY_COMMENT_NOTIFY_ADMIN = "comment.notify_admin";
export const KEY_COMMENT_NOTIFY_REPLY = "comment.notify_reply";
export const KEY_COMMENT_SMTP_SENDER_NAME = "comment.smtp_sender_name";
export const KEY_COMMENT_SMTP_SENDER_EMAIL = "comment.smtp_sender_email";
export const KEY_COMMENT_SMTP_HOST = "comment.smtp_host";
export const KEY_COMMENT_SMTP_PORT = "comment.smtp_port";
export const KEY_COMMENT_SMTP_USER = "comment.smtp_user";
export const KEY_COMMENT_SMTP_PASS = "comment.smtp_pass";
export const KEY_COMMENT_SMTP_SECURE = "comment.smtp_secure";
export const KEY_PUSHOO_CHANNEL = "pushoo.channel";
export const KEY_PUSHOO_URL = "pushoo.url";
export const KEY_WEBHOOK_REQUEST_BODY = "webhook.request_body";
export const KEY_WEBHOOK_HEADERS = "webhook.headers";
export const KEY_SC_MAIL_NOTIFY = "sc.mail_notify";
export const KEY_COMMENT_MAIL_SUBJECT = "comment.mail_subject";
export const KEY_COMMENT_MAIL_TEMPLATE = "comment.mail_template";
export const KEY_COMMENT_MAIL_SUBJECT_ADMIN = "comment.mail_subject_admin";
export const KEY_COMMENT_MAIL_TEMPLATE_ADMIN = "comment.mail_template_admin";

// ==================== 邮件服务配置 ====================
export const KEY_SMTP_HOST = "SMTP_HOST";
export const KEY_SMTP_PORT = "SMTP_PORT";
export const KEY_SMTP_USERNAME = "SMTP_USERNAME";
export const KEY_SMTP_PASSWORD = "SMTP_PASSWORD";
export const KEY_SMTP_SENDER_NAME = "SMTP_SENDER_NAME";
export const KEY_SMTP_SENDER_EMAIL = "SMTP_SENDER_EMAIL";
export const KEY_SMTP_REPLY_TO_EMAIL = "SMTP_REPLY_TO_EMAIL";
export const KEY_SMTP_FORCE_SSL = "SMTP_FORCE_SSL";
export const KEY_RESET_PASSWORD_SUBJECT = "DEFAULT_RESET_PASSWORD_SUBJECT";
export const KEY_RESET_PASSWORD_TEMPLATE = "DEFAULT_RESET_PASSWORD_TEMPLATE";
export const KEY_ACTIVATE_ACCOUNT_SUBJECT = "DEFAULT_ACTIVATE_ACCOUNT_SUBJECT";
export const KEY_ACTIVATE_ACCOUNT_TEMPLATE = "DEFAULT_ACTIVATE_ACCOUNT_TEMPLATE";
export const KEY_ENABLE_USER_ACTIVATION = "ENABLE_USER_ACTIVATION";
export const KEY_IP_API = "IP_API";
export const KEY_IP_API_TOKEN = "IP_API_TOKEN";

// ==================== 第三方登录 (PRO) ====================
export const KEY_QQ_ENABLE = "oauth.qq.enable";
export const KEY_QQ_APP_ID = "oauth.qq.app_id";
export const KEY_QQ_APP_KEY = "oauth.qq.app_key";
export const KEY_QQ_AUTO_REGISTER = "oauth.qq.auto_register";
export const KEY_QQ_CALLBACK_URL = "oauth.qq.callback_url";
export const KEY_WECHAT_ENABLE = "oauth.wechat.enable";
export const KEY_WECHAT_APP_ID = "oauth.wechat.app_id";
export const KEY_WECHAT_APP_SECRET = "oauth.wechat.app_secret";
export const KEY_WECHAT_LOGIN_MODE = "oauth.wechat.login_mode";
export const KEY_WECHAT_TOKEN = "oauth.wechat.token";
export const KEY_WECHAT_ENCODING_AES_KEY = "oauth.wechat.encoding_aes_key";
export const KEY_WECHAT_QRCODE_LOGIN_REPLY = "oauth.wechat.qrcode_login_reply";
export const KEY_WECHAT_QRCODE_BIND_REPLY = "oauth.wechat.qrcode_bind_reply";
export const KEY_WECHAT_AUTO_REGISTER = "oauth.wechat.auto_register";
export const KEY_WECHAT_CALLBACK_URL = "oauth.wechat.callback_url";
export const KEY_LOGTO_ENABLE = "oauth.logto.enable";
export const KEY_LOGTO_APP_ID = "oauth.logto.app_id";
export const KEY_LOGTO_APP_SECRET = "oauth.logto.app_secret";
export const KEY_LOGTO_ENDPOINT = "oauth.logto.endpoint";
export const KEY_LOGTO_DIRECT_CONNECTOR = "oauth.logto.direct_connector";
export const KEY_LOGTO_DISPLAY_NAME = "oauth.logto.display_name";
export const KEY_LOGTO_AUTO_REGISTER = "oauth.logto.auto_register";
export const KEY_LOGTO_CALLBACK_URL = "oauth.logto.callback_url";
export const KEY_OIDC_ENABLE = "oauth.oidc.enable";
export const KEY_OIDC_CLIENT_ID = "oauth.oidc.client_id";
export const KEY_OIDC_CLIENT_SECRET = "oauth.oidc.client_secret";
export const KEY_OIDC_SCOPE = "oauth.oidc.scope";
export const KEY_OIDC_WELLKNOWN = "oauth.oidc.wellknown";
export const KEY_OIDC_DISPLAY_NAME = "oauth.oidc.display_name";
export const KEY_OIDC_AUTO_REGISTER = "oauth.oidc.auto_register";
export const KEY_OIDC_CALLBACK_URL = "oauth.oidc.callback_url";
export const KEY_RAINBOW_ENABLE = "oauth.rainbow.enable";
export const KEY_RAINBOW_API_URL = "oauth.rainbow.api_url";
export const KEY_RAINBOW_APP_ID = "oauth.rainbow.app_id";
export const KEY_RAINBOW_APP_KEY = "oauth.rainbow.app_key";
export const KEY_RAINBOW_LOGIN_METHODS = "oauth.rainbow.login_methods";
export const KEY_RAINBOW_CALLBACK_URL = "oauth.rainbow.callback_url";

// ==================== SEO 推送 (PRO) ====================
export const KEY_SEO_AUTO_SUBMIT = "seo.auto_submit";
export const KEY_SEO_BAIDU_ENABLE = "seo.baidu.enable";
export const KEY_SEO_BAIDU_SITE = "seo.baidu.site";
export const KEY_SEO_BAIDU_TOKEN = "seo.baidu.token";
export const KEY_SEO_BING_ENABLE = "seo.bing.enable";
export const KEY_SEO_BING_API_KEY = "seo.bing.api_key";
export const KEY_SEO_BING_SITE_URL = "seo.bing.site_url";
export const KEY_SEO_GOOGLE_ENABLE = "seo.google.enable";
export const KEY_SEO_GOOGLE_CREDENTIAL = "seo.google.credential";
export const KEY_SEO_RETRY_TIMES = "seo.retry_times";
export const KEY_SEO_RETRY_INTERVAL = "seo.retry_interval";

// ==================== 友链配置 ====================
export const KEY_FRIEND_LINK_DEFAULT_CATEGORY = "FRIEND_LINK_DEFAULTCATEGORY";
export const KEY_FRIEND_LINK_APPLY_CONDITION = "FRIEND_LINK_APPLY_CONDITION";
export const KEY_FRIEND_LINK_APPLY_CUSTOM_CODE = "FRIEND_LINK_APPLY_CUSTOM_CODE";
export const KEY_FRIEND_LINK_APPLY_CUSTOM_CODE_HTML = "FRIEND_LINK_APPLY_CUSTOM_CODE_HTML";
export const KEY_FRIEND_LINK_PLACEHOLDER_NAME = "FRIEND_LINK_PLACEHOLDER_NAME";
export const KEY_FRIEND_LINK_PLACEHOLDER_URL = "FRIEND_LINK_PLACEHOLDER_URL";
export const KEY_FRIEND_LINK_PLACEHOLDER_LOGO = "FRIEND_LINK_PLACEHOLDER_LOGO";
export const KEY_FRIEND_LINK_PLACEHOLDER_DESC = "FRIEND_LINK_PLACEHOLDER_DESCRIPTION";
export const KEY_FRIEND_LINK_PLACEHOLDER_SITESHOT = "FRIEND_LINK_PLACEHOLDER_SITESHOT";
export const KEY_FRIEND_LINK_NOTIFY_ADMIN = "FRIEND_LINK_NOTIFY_ADMIN";
export const KEY_FRIEND_LINK_SC_MAIL_NOTIFY = "FRIEND_LINK_SC_MAIL_NOTIFY";
export const KEY_FRIEND_LINK_PUSHOO_CHANNEL = "FRIEND_LINK_PUSHOO_CHANNEL";
export const KEY_FRIEND_LINK_PUSHOO_URL = "FRIEND_LINK_PUSHOO_URL";
export const KEY_FRIEND_LINK_WEBHOOK_BODY = "FRIEND_LINK_WEBHOOK_REQUEST_BODY";
export const KEY_FRIEND_LINK_WEBHOOK_HEADERS = "FRIEND_LINK_WEBHOOK_HEADERS";
export const KEY_FRIEND_LINK_MAIL_SUBJECT_ADMIN = "FRIEND_LINK_MAIL_SUBJECT_ADMIN";
export const KEY_FRIEND_LINK_MAIL_TEMPLATE_ADMIN = "FRIEND_LINK_MAIL_TEMPLATE_ADMIN";
export const KEY_FRIEND_LINK_REVIEW_MAIL_ENABLE = "FRIEND_LINK_REVIEW_MAIL_ENABLE";
export const KEY_FRIEND_LINK_REVIEW_MAIL_SUBJECT_APPROVED = "FRIEND_LINK_REVIEW_MAIL_SUBJECT_APPROVED";
export const KEY_FRIEND_LINK_REVIEW_MAIL_TEMPLATE_APPROVED = "FRIEND_LINK_REVIEW_MAIL_TEMPLATE_APPROVED";
export const KEY_FRIEND_LINK_REVIEW_MAIL_SUBJECT_REJECTED = "FRIEND_LINK_REVIEW_MAIL_SUBJECT_REJECTED";
export const KEY_FRIEND_LINK_REVIEW_MAIL_TEMPLATE_REJECTED = "FRIEND_LINK_REVIEW_MAIL_TEMPLATE_REJECTED";

// ==================== 关于页面配置 ====================
export const KEY_ABOUT_NAME = "about.page.name";
export const KEY_ABOUT_DESCRIPTION = "about.page.description";
export const KEY_ABOUT_AVATAR_IMG = "about.page.avatar_img";
export const KEY_ABOUT_SUBTITLE = "about.page.subtitle";
export const KEY_ABOUT_AVATAR_SKILLS_LEFT = "about.page.avatar_skills_left";
export const KEY_ABOUT_AVATAR_SKILLS_RIGHT = "about.page.avatar_skills_right";
export const KEY_ABOUT_SITE_TIPS = "about.page.about_site_tips";
export const KEY_ABOUT_MAP = "about.page.map";
export const KEY_ABOUT_SELF_INFO = "about.page.self_info";
export const KEY_ABOUT_PERSONALITIES = "about.page.personalities";
export const KEY_ABOUT_MAXIM = "about.page.maxim";
export const KEY_ABOUT_BUFF = "about.page.buff";
export const KEY_ABOUT_GAME = "about.page.game";
export const KEY_ABOUT_COMIC = "about.page.comic";
export const KEY_ABOUT_LIKE = "about.page.like";
export const KEY_ABOUT_MUSIC = "about.page.music";
export const KEY_ABOUT_CAREERS = "about.page.careers";
export const KEY_ABOUT_SKILLS_TIPS = "about.page.skills_tips";
export const KEY_ABOUT_STATISTICS_BG = "about.page.statistics_background";
export const KEY_ABOUT_CUSTOM_CODE = "about.page.custom_code";
export const KEY_ABOUT_CUSTOM_CODE_HTML = "about.page.custom_code_html";
export const KEY_ABOUT_ENABLE_AUTHOR_BOX = "about.page.enable.author_box";
export const KEY_ABOUT_ENABLE_PAGE_CONTENT = "about.page.enable.page_content";
export const KEY_ABOUT_ENABLE_SKILLS = "about.page.enable.skills";
export const KEY_ABOUT_ENABLE_CAREERS = "about.page.enable.careers";
export const KEY_ABOUT_ENABLE_STATISTIC = "about.page.enable.statistic";
export const KEY_ABOUT_ENABLE_MAP_INFO = "about.page.enable.map_and_info";
export const KEY_ABOUT_ENABLE_PERSONALITY = "about.page.enable.personality";
export const KEY_ABOUT_ENABLE_PHOTO = "about.page.enable.photo";
export const KEY_ABOUT_ENABLE_MAXIM = "about.page.enable.maxim";
export const KEY_ABOUT_ENABLE_BUFF = "about.page.enable.buff";
export const KEY_ABOUT_ENABLE_GAME = "about.page.enable.game";
export const KEY_ABOUT_ENABLE_COMIC = "about.page.enable.comic";
export const KEY_ABOUT_ENABLE_LIKE_TECH = "about.page.enable.like_tech";
export const KEY_ABOUT_ENABLE_MUSIC = "about.page.enable.music";
export const KEY_ABOUT_ENABLE_CUSTOM_CODE = "about.page.enable.custom_code";
export const KEY_ABOUT_ENABLE_COMMENT = "about.page.enable.comment";

// ==================== 装备页面配置 ====================
export const KEY_EQUIPMENT_BANNER_BG = "equipment.banner.background";
export const KEY_EQUIPMENT_BANNER_TITLE = "equipment.banner.title";
export const KEY_EQUIPMENT_BANNER_DESC = "equipment.banner.description";
export const KEY_EQUIPMENT_BANNER_TIP = "equipment.banner.tip";
export const KEY_EQUIPMENT_LIST = "equipment.list";

// ==================== 最近评论页面配置 ====================
export const KEY_RECENT_COMMENTS_BANNER_BG = "recent_comments.banner.background";
export const KEY_RECENT_COMMENTS_BANNER_TITLE = "recent_comments.banner.title";
export const KEY_RECENT_COMMENTS_BANNER_DESC = "recent_comments.banner.description";
export const KEY_RECENT_COMMENTS_BANNER_TIP = "recent_comments.banner.tip";

// ==================== 即刻配置 (PRO) ====================
export const KEY_ESSAY_TITLE = "essay.title";
export const KEY_ESSAY_SUBTITLE = "essay.subtitle";
export const KEY_ESSAY_TIPS = "essay.tips";
export const KEY_ESSAY_BUTTON_TEXT = "essay.button_text";
export const KEY_ESSAY_BUTTON_LINK = "essay.button_link";
export const KEY_ESSAY_LIMIT = "essay.limit";
export const KEY_ESSAY_HOME_ENABLE = "essay.home_enable";
export const KEY_ESSAY_TOP_BACKGROUND = "essay.top_background";

// ==================== 朋友圈配置 (PRO) ====================
export const KEY_MOMENTS_ENABLE = "moments.enable";
export const KEY_MOMENTS_TITLE = "moments.title";
export const KEY_MOMENTS_SUBTITLE = "moments.subtitle";
export const KEY_MOMENTS_TIPS = "moments.tips";
export const KEY_MOMENTS_BUTTON_TEXT = "moments.button_text";
export const KEY_MOMENTS_BUTTON_LINK = "moments.button_link";
export const KEY_MOMENTS_TOP_BACKGROUND = "moments.top_background";
export const KEY_MOMENTS_FETCH_INTERVAL = "moments.fetch_interval";
export const KEY_MOMENTS_MAX_ITEMS = "moments.max_items";
export const KEY_MOMENTS_DISPLAY_LIMIT = "moments.display_limit";
export const KEY_MOMENTS_CACHE_DURATION = "moments.cache_duration";
export const KEY_MOMENTS_RSS_TIMEOUT = "moments.rss_timeout";
export const KEY_MOMENTS_MIN_FETCH_INTERVAL = "moments.min_fetch_interval";
export const KEY_MOMENTS_NOTIFY_ADMIN = "moments.notify_admin";
export const KEY_MOMENTS_SC_MAIL_NOTIFY = "moments.sc_mail_notify";
export const KEY_MOMENTS_PUSHOO_CHANNEL = "moments.pushoo.channel";
export const KEY_MOMENTS_PUSHOO_URL = "moments.pushoo.url";
export const KEY_MOMENTS_WEBHOOK_BODY = "moments.webhook.request_body";
export const KEY_MOMENTS_WEBHOOK_HEADERS = "moments.webhook.headers";
export const KEY_MOMENTS_MAIL_SUBJECT_ADMIN = "moments.mail_subject_admin";
export const KEY_MOMENTS_MAIL_TEMPLATE_ADMIN = "moments.mail_template_admin";

// ==================== 相册页面配置 ====================
export const KEY_ALBUM_BANNER_BG = "album.banner.background";
export const KEY_ALBUM_BANNER_TITLE = "album.banner.title";
export const KEY_ALBUM_BANNER_DESC = "album.banner.description";
export const KEY_ALBUM_BANNER_TIP = "album.banner.tip";
export const KEY_ALBUM_LAYOUT_MODE = "album.layout_mode";
export const KEY_ALBUM_WATERFALL_COLUMNS = "album.waterfall.column_count";
export const KEY_ALBUM_WATERFALL_GAP = "album.waterfall.gap";
export const KEY_ALBUM_PAGE_SIZE = "album.page_size";
export const KEY_ALBUM_ENABLE_COMMENT = "album.enable_comment";
export const KEY_ALBUM_API_URL = "album.api_url";
export const KEY_ALBUM_DEFAULT_THUMB_PARAM = "album.default_thumb_param";
export const KEY_ALBUM_DEFAULT_BIG_PARAM = "album.default_big_param";
export const KEY_ALBUM_ABOUT_LINK = "album.about_link";

// ==================== 音乐页面配置 ====================
export const KEY_MUSIC_PLAYER_ENABLE = "music.player.enable";
export const KEY_MUSIC_PLAYER_PLAYLIST_ID = "music.player.playlist_id";
export const KEY_MUSIC_PLAYER_CUSTOM_PLAYLIST = "music.player.custom_playlist";
export const KEY_MUSIC_CAPSULE_CUSTOM_PLAYLIST = "music.capsule.custom_playlist";
export const KEY_MUSIC_API_BASE_URL = "music.api.base_url";
export const KEY_MUSIC_VINYL_BACKGROUND = "music.vinyl.background";
export const KEY_MUSIC_VINYL_OUTER = "music.vinyl.outer";
export const KEY_MUSIC_VINYL_INNER = "music.vinyl.inner";
export const KEY_MUSIC_VINYL_NEEDLE = "music.vinyl.needle";
export const KEY_MUSIC_VINYL_GROOVE = "music.vinyl.groove";

// ==================== 人机验证配置 ====================
export const KEY_CAPTCHA_PROVIDER = "captcha.provider";
export const KEY_TURNSTILE_ENABLE = "turnstile.enable";
export const KEY_TURNSTILE_SITE_KEY = "turnstile.site_key";
export const KEY_TURNSTILE_SECRET_KEY = "turnstile.secret_key";
export const KEY_GEETEST_CAPTCHA_ID = "geetest.captcha_id";
export const KEY_GEETEST_CAPTCHA_KEY = "geetest.captcha_key";
export const KEY_IMAGE_CAPTCHA_LENGTH = "image_captcha.length";
export const KEY_IMAGE_CAPTCHA_EXPIRE = "image_captcha.expire";

// ==================== 微信分享配置 ====================
export const KEY_WECHAT_SHARE_ENABLE = "wechat.share.enable";
export const KEY_WECHAT_SHARE_APP_ID = "wechat.share.app_id";
export const KEY_WECHAT_SHARE_APP_SECRET = "wechat.share.app_secret";

// ==================== AI 配置 (PRO) ====================
export const KEY_AI_PROFILES = "ai_profiles";
export const KEY_AI_DEFAULT_PROFILE_ID = "ai_default_profile_id";
export const KEY_AI_SUMMARY_PROVIDER = "ai_summary_provider";
export const KEY_AI_SUMMARY_API_KEY = "ai_summary_api_key";
export const KEY_AI_SUMMARY_API_URL = "ai_summary_api_url";
export const KEY_AI_SUMMARY_MODEL = "ai_summary_model";
export const KEY_AI_SUMMARY_SYSTEM_PROMPT = "ai_summary_system_prompt";
export const KEY_AI_WRITING_PROVIDER = "ai_writing_provider";
export const KEY_AI_WRITING_API_KEY = "ai_writing_api_key";
export const KEY_AI_WRITING_API_URL = "ai_writing_api_url";
export const KEY_AI_WRITING_MODEL = "ai_writing_model";
export const KEY_AI_WRITING_SYSTEM_PROMPT = "ai_writing_system_prompt";
export const KEY_AI_WRITING_MAX_TOKENS = "ai_writing_max_tokens";
export const KEY_AI_WRITING_TEMPERATURE = "ai_writing_temperature";
export const KEY_AI_PODCAST_ENABLE = "ai_podcast.enable";
export const KEY_AI_PODCAST_PROVIDER = "ai_podcast.provider";
export const KEY_AI_PODCAST_APP_ID = "ai_podcast.app_id";
export const KEY_AI_PODCAST_ACCESS_KEY = "ai_podcast.access_key";
export const KEY_AI_PODCAST_RESOURCE_ID = "ai_podcast.resource_id";
export const KEY_AI_PODCAST_SPEAKER1 = "ai_podcast.speaker1";
export const KEY_AI_PODCAST_SPEAKER2 = "ai_podcast.speaker2";
export const KEY_AI_PODCAST_USE_HEAD_MUSIC = "ai_podcast.use_head_music";
export const KEY_AI_PODCAST_USE_TAIL_MUSIC = "ai_podcast.use_tail_music";
export const KEY_AI_PODCAST_AUDIO_FORMAT = "ai_podcast.audio_format";
export const KEY_AI_PODCAST_SAMPLE_RATE = "ai_podcast.sample_rate";
export const KEY_AI_PODCAST_SPEECH_RATE = "ai_podcast.speech_rate";
export const KEY_AI_PODCAST_BUTTON_TEXT = "ai_podcast.button_text";
export const KEY_AI_PODCAST_BUTTON_ICON = "ai_podcast.button_icon";
export const KEY_AI_ASSISTANT_ENABLE = "ai_assistant.enable";
export const KEY_AI_ASSISTANT_NAME = "ai_assistant.name";
export const KEY_AI_ASSISTANT_WELCOME = "ai_assistant.welcome";
export const KEY_AI_ASSISTANT_CHAT_SUGGESTIONS = "ai_assistant.chat_suggestions";
export const KEY_AI_ASSISTANT_SEARCH_SUGGESTIONS = "ai_assistant.search_suggestions";
export const KEY_AI_ASSISTANT_EMBEDDING_PROVIDER = "ai_assistant.embedding_provider";
export const KEY_AI_ASSISTANT_EMBEDDING_API_KEY = "ai_assistant.embedding_api_key";
export const KEY_AI_ASSISTANT_EMBEDDING_MODEL = "ai_assistant.embedding_model";
export const KEY_AI_ASSISTANT_VECTOR_STORE = "ai_assistant.vector_store";
export const KEY_AI_ASSISTANT_SYSTEM_PROMPT = "ai_assistant.system_prompt";
export const KEY_AI_ASSISTANT_USER_PROMPT = "ai_assistant.user_prompt";
export const KEY_AI_ASSISTANT_NO_CONTEXT_PROMPT = "ai_assistant.no_context_prompt";
