// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/article"
	"github.com/anzhiyu-c/anheyu-app/ent/articlehistory"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ArticleHistoryUpdate is the builder for updating ArticleHistory entities.
type ArticleHistoryUpdate struct {
	config
	hooks     []Hook
	mutation  *ArticleHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ArticleHistoryUpdate builder.
func (_u *ArticleHistoryUpdate) Where(ps ...predicate.ArticleHistory) *ArticleHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *ArticleHistoryUpdate) SetArticleID(v uint) *ArticleHistoryUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableArticleID(v *uint) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ArticleHistoryUpdate) SetVersion(v int) *ArticleHistoryUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableVersion(v *int) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ArticleHistoryUpdate) AddVersion(v int) *ArticleHistoryUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleHistoryUpdate) SetTitle(v string) *ArticleHistoryUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableTitle(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContentMd sets the "content_md" field.
func (_u *ArticleHistoryUpdate) SetContentMd(v string) *ArticleHistoryUpdate {
	_u.mutation.SetContentMd(v)
	return _u
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableContentMd(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetContentMd(*v)
	}
	return _u
}

// ClearContentMd clears the value of the "content_md" field.
func (_u *ArticleHistoryUpdate) ClearContentMd() *ArticleHistoryUpdate {
	_u.mutation.ClearContentMd()
	return _u
}

// SetContentHTML sets the "content_html" field.
func (_u *ArticleHistoryUpdate) SetContentHTML(v string) *ArticleHistoryUpdate {
	_u.mutation.SetContentHTML(v)
	return _u
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableContentHTML(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetContentHTML(*v)
	}
	return _u
}

// ClearContentHTML clears the value of the "content_html" field.
func (_u *ArticleHistoryUpdate) ClearContentHTML() *ArticleHistoryUpdate {
	_u.mutation.ClearContentHTML()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *ArticleHistoryUpdate) SetCoverURL(v string) *ArticleHistoryUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableCoverURL(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *ArticleHistoryUpdate) ClearCoverURL() *ArticleHistoryUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetTopImgURL sets the "top_img_url" field.
func (_u *ArticleHistoryUpdate) SetTopImgURL(v string) *ArticleHistoryUpdate {
	_u.mutation.SetTopImgURL(v)
	return _u
}

// SetNillableTopImgURL sets the "top_img_url" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableTopImgURL(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetTopImgURL(*v)
	}
	return _u
}

// ClearTopImgURL clears the value of the "top_img_url" field.
func (_u *ArticleHistoryUpdate) ClearTopImgURL() *ArticleHistoryUpdate {
	_u.mutation.ClearTopImgURL()
	return _u
}

// SetPrimaryColor sets the "primary_color" field.
func (_u *ArticleHistoryUpdate) SetPrimaryColor(v string) *ArticleHistoryUpdate {
	_u.mutation.SetPrimaryColor(v)
	return _u
}

// SetNillablePrimaryColor sets the "primary_color" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillablePrimaryColor(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetPrimaryColor(*v)
	}
	return _u
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (_u *ArticleHistoryUpdate) ClearPrimaryColor() *ArticleHistoryUpdate {
	_u.mutation.ClearPrimaryColor()
	return _u
}

// SetSummaries sets the "summaries" field.
func (_u *ArticleHistoryUpdate) SetSummaries(v []string) *ArticleHistoryUpdate {
	_u.mutation.SetSummaries(v)
	return _u
}

// AppendSummaries appends value to the "summaries" field.
func (_u *ArticleHistoryUpdate) AppendSummaries(v []string) *ArticleHistoryUpdate {
	_u.mutation.AppendSummaries(v)
	return _u
}

// ClearSummaries clears the value of the "summaries" field.
func (_u *ArticleHistoryUpdate) ClearSummaries() *ArticleHistoryUpdate {
	_u.mutation.ClearSummaries()
	return _u
}

// SetWordCount sets the "word_count" field.
func (_u *ArticleHistoryUpdate) SetWordCount(v int) *ArticleHistoryUpdate {
	_u.mutation.ResetWordCount()
	_u.mutation.SetWordCount(v)
	return _u
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableWordCount(v *int) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetWordCount(*v)
	}
	return _u
}

// AddWordCount adds value to the "word_count" field.
func (_u *ArticleHistoryUpdate) AddWordCount(v int) *ArticleHistoryUpdate {
	_u.mutation.AddWordCount(v)
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *ArticleHistoryUpdate) SetKeywords(v string) *ArticleHistoryUpdate {
	_u.mutation.SetKeywords(v)
	return _u
}

// SetNillableKeywords sets the "keywords" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableKeywords(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetKeywords(*v)
	}
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *ArticleHistoryUpdate) ClearKeywords() *ArticleHistoryUpdate {
	_u.mutation.ClearKeywords()
	return _u
}

// SetEditorID sets the "editor_id" field.
func (_u *ArticleHistoryUpdate) SetEditorID(v uint) *ArticleHistoryUpdate {
	_u.mutation.ResetEditorID()
	_u.mutation.SetEditorID(v)
	return _u
}

// SetNillableEditorID sets the "editor_id" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableEditorID(v *uint) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetEditorID(*v)
	}
	return _u
}

// AddEditorID adds value to the "editor_id" field.
func (_u *ArticleHistoryUpdate) AddEditorID(v int) *ArticleHistoryUpdate {
	_u.mutation.AddEditorID(v)
	return _u
}

// SetEditorNickname sets the "editor_nickname" field.
func (_u *ArticleHistoryUpdate) SetEditorNickname(v string) *ArticleHistoryUpdate {
	_u.mutation.SetEditorNickname(v)
	return _u
}

// SetNillableEditorNickname sets the "editor_nickname" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableEditorNickname(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetEditorNickname(*v)
	}
	return _u
}

// ClearEditorNickname clears the value of the "editor_nickname" field.
func (_u *ArticleHistoryUpdate) ClearEditorNickname() *ArticleHistoryUpdate {
	_u.mutation.ClearEditorNickname()
	return _u
}

// SetChangeNote sets the "change_note" field.
func (_u *ArticleHistoryUpdate) SetChangeNote(v string) *ArticleHistoryUpdate {
	_u.mutation.SetChangeNote(v)
	return _u
}

// SetNillableChangeNote sets the "change_note" field if the given value is not nil.
func (_u *ArticleHistoryUpdate) SetNillableChangeNote(v *string) *ArticleHistoryUpdate {
	if v != nil {
		_u.SetChangeNote(*v)
	}
	return _u
}

// ClearChangeNote clears the value of the "change_note" field.
func (_u *ArticleHistoryUpdate) ClearChangeNote() *ArticleHistoryUpdate {
	_u.mutation.ClearChangeNote()
	return _u
}

// SetExtraData sets the "extra_data" field.
func (_u *ArticleHistoryUpdate) SetExtraData(v map[string]interface{}) *ArticleHistoryUpdate {
	_u.mutation.SetExtraData(v)
	return _u
}

// ClearExtraData clears the value of the "extra_data" field.
func (_u *ArticleHistoryUpdate) ClearExtraData() *ArticleHistoryUpdate {
	_u.mutation.ClearExtraData()
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *ArticleHistoryUpdate) SetArticle(v *Article) *ArticleHistoryUpdate {
	return _u.SetArticleID(v.ID)
}

// Mutation returns the ArticleHistoryMutation object of the builder.
func (_u *ArticleHistoryUpdate) Mutation() *ArticleHistoryMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *ArticleHistoryUpdate) ClearArticle() *ArticleHistoryUpdate {
	_u.mutation.ClearArticle()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleHistoryUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := articlehistory.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := articlehistory.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WordCount(); ok {
		if err := articlehistory.WordCountValidator(v); err != nil {
			return &ValidationError{Name: "word_count", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.word_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeNote(); ok {
		if err := articlehistory.ChangeNoteValidator(v); err != nil {
			return &ValidationError{Name: "change_note", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.change_note": %w`, err)}
		}
	}
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleHistory.article"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ArticleHistoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticleHistoryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ArticleHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articlehistory.Table, articlehistory.Columns, sqlgraph.NewFieldSpec(articlehistory.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(articlehistory.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(articlehistory.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(articlehistory.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentMd(); ok {
		_spec.SetField(articlehistory.FieldContentMd, field.TypeString, value)
	}
	if _u.mutation.ContentMdCleared() {
		_spec.ClearField(articlehistory.FieldContentMd, field.TypeString)
	}
	if value, ok := _u.mutation.ContentHTML(); ok {
		_spec.SetField(articlehistory.FieldContentHTML, field.TypeString, value)
	}
	if _u.mutation.ContentHTMLCleared() {
		_spec.ClearField(articlehistory.FieldContentHTML, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(articlehistory.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(articlehistory.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.TopImgURL(); ok {
		_spec.SetField(articlehistory.FieldTopImgURL, field.TypeString, value)
	}
	if _u.mutation.TopImgURLCleared() {
		_spec.ClearField(articlehistory.FieldTopImgURL, field.TypeString)
	}
	if value, ok := _u.mutation.PrimaryColor(); ok {
		_spec.SetField(articlehistory.FieldPrimaryColor, field.TypeString, value)
	}
	if _u.mutation.PrimaryColorCleared() {
		_spec.ClearField(articlehistory.FieldPrimaryColor, field.TypeString)
	}
	if value, ok := _u.mutation.Summaries(); ok {
		_spec.SetField(articlehistory.FieldSummaries, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSummaries(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, articlehistory.FieldSummaries, value)
		})
	}
	if _u.mutation.SummariesCleared() {
		_spec.ClearField(articlehistory.FieldSummaries, field.TypeJSON)
	}
	if value, ok := _u.mutation.WordCount(); ok {
		_spec.SetField(articlehistory.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWordCount(); ok {
		_spec.AddField(articlehistory.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(articlehistory.FieldKeywords, field.TypeString, value)
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(articlehistory.FieldKeywords, field.TypeString)
	}
	if value, ok := _u.mutation.EditorID(); ok {
		_spec.SetField(articlehistory.FieldEditorID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedEditorID(); ok {
		_spec.AddField(articlehistory.FieldEditorID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.EditorNickname(); ok {
		_spec.SetField(articlehistory.FieldEditorNickname, field.TypeString, value)
	}
	if _u.mutation.EditorNicknameCleared() {
		_spec.ClearField(articlehistory.FieldEditorNickname, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeNote(); ok {
		_spec.SetField(articlehistory.FieldChangeNote, field.TypeString, value)
	}
	if _u.mutation.ChangeNoteCleared() {
		_spec.ClearField(articlehistory.FieldChangeNote, field.TypeString)
	}
	if value, ok := _u.mutation.ExtraData(); ok {
		_spec.SetField(articlehistory.FieldExtraData, field.TypeJSON, value)
	}
	if _u.mutation.ExtraDataCleared() {
		_spec.ClearField(articlehistory.FieldExtraData, field.TypeJSON)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articlehistory.ArticleTable,
			Columns: []string{articlehistory.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articlehistory.ArticleTable,
			Columns: []string{articlehistory.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articlehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleHistoryUpdateOne is the builder for updating a single ArticleHistory entity.
type ArticleHistoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ArticleHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetArticleID sets the "article_id" field.
func (_u *ArticleHistoryUpdateOne) SetArticleID(v uint) *ArticleHistoryUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableArticleID(v *uint) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ArticleHistoryUpdateOne) SetVersion(v int) *ArticleHistoryUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableVersion(v *int) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ArticleHistoryUpdateOne) AddVersion(v int) *ArticleHistoryUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleHistoryUpdateOne) SetTitle(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableTitle(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContentMd sets the "content_md" field.
func (_u *ArticleHistoryUpdateOne) SetContentMd(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetContentMd(v)
	return _u
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableContentMd(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetContentMd(*v)
	}
	return _u
}

// ClearContentMd clears the value of the "content_md" field.
func (_u *ArticleHistoryUpdateOne) ClearContentMd() *ArticleHistoryUpdateOne {
	_u.mutation.ClearContentMd()
	return _u
}

// SetContentHTML sets the "content_html" field.
func (_u *ArticleHistoryUpdateOne) SetContentHTML(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetContentHTML(v)
	return _u
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableContentHTML(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetContentHTML(*v)
	}
	return _u
}

// ClearContentHTML clears the value of the "content_html" field.
func (_u *ArticleHistoryUpdateOne) ClearContentHTML() *ArticleHistoryUpdateOne {
	_u.mutation.ClearContentHTML()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *ArticleHistoryUpdateOne) SetCoverURL(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableCoverURL(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *ArticleHistoryUpdateOne) ClearCoverURL() *ArticleHistoryUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetTopImgURL sets the "top_img_url" field.
func (_u *ArticleHistoryUpdateOne) SetTopImgURL(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetTopImgURL(v)
	return _u
}

// SetNillableTopImgURL sets the "top_img_url" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableTopImgURL(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetTopImgURL(*v)
	}
	return _u
}

// ClearTopImgURL clears the value of the "top_img_url" field.
func (_u *ArticleHistoryUpdateOne) ClearTopImgURL() *ArticleHistoryUpdateOne {
	_u.mutation.ClearTopImgURL()
	return _u
}

// SetPrimaryColor sets the "primary_color" field.
func (_u *ArticleHistoryUpdateOne) SetPrimaryColor(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetPrimaryColor(v)
	return _u
}

// SetNillablePrimaryColor sets the "primary_color" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillablePrimaryColor(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetPrimaryColor(*v)
	}
	return _u
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (_u *ArticleHistoryUpdateOne) ClearPrimaryColor() *ArticleHistoryUpdateOne {
	_u.mutation.ClearPrimaryColor()
	return _u
}

// SetSummaries sets the "summaries" field.
func (_u *ArticleHistoryUpdateOne) SetSummaries(v []string) *ArticleHistoryUpdateOne {
	_u.mutation.SetSummaries(v)
	return _u
}

// AppendSummaries appends value to the "summaries" field.
func (_u *ArticleHistoryUpdateOne) AppendSummaries(v []string) *ArticleHistoryUpdateOne {
	_u.mutation.AppendSummaries(v)
	return _u
}

// ClearSummaries clears the value of the "summaries" field.
func (_u *ArticleHistoryUpdateOne) ClearSummaries() *ArticleHistoryUpdateOne {
	_u.mutation.ClearSummaries()
	return _u
}

// SetWordCount sets the "word_count" field.
func (_u *ArticleHistoryUpdateOne) SetWordCount(v int) *ArticleHistoryUpdateOne {
	_u.mutation.ResetWordCount()
	_u.mutation.SetWordCount(v)
	return _u
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableWordCount(v *int) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetWordCount(*v)
	}
	return _u
}

// AddWordCount adds value to the "word_count" field.
func (_u *ArticleHistoryUpdateOne) AddWordCount(v int) *ArticleHistoryUpdateOne {
	_u.mutation.AddWordCount(v)
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *ArticleHistoryUpdateOne) SetKeywords(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetKeywords(v)
	return _u
}

// SetNillableKeywords sets the "keywords" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableKeywords(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetKeywords(*v)
	}
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *ArticleHistoryUpdateOne) ClearKeywords() *ArticleHistoryUpdateOne {
	_u.mutation.ClearKeywords()
	return _u
}

// SetEditorID sets the "editor_id" field.
func (_u *ArticleHistoryUpdateOne) SetEditorID(v uint) *ArticleHistoryUpdateOne {
	_u.mutation.ResetEditorID()
	_u.mutation.SetEditorID(v)
	return _u
}

// SetNillableEditorID sets the "editor_id" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableEditorID(v *uint) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetEditorID(*v)
	}
	return _u
}

// AddEditorID adds value to the "editor_id" field.
func (_u *ArticleHistoryUpdateOne) AddEditorID(v int) *ArticleHistoryUpdateOne {
	_u.mutation.AddEditorID(v)
	return _u
}

// SetEditorNickname sets the "editor_nickname" field.
func (_u *ArticleHistoryUpdateOne) SetEditorNickname(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetEditorNickname(v)
	return _u
}

// SetNillableEditorNickname sets the "editor_nickname" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableEditorNickname(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetEditorNickname(*v)
	}
	return _u
}

// ClearEditorNickname clears the value of the "editor_nickname" field.
func (_u *ArticleHistoryUpdateOne) ClearEditorNickname() *ArticleHistoryUpdateOne {
	_u.mutation.ClearEditorNickname()
	return _u
}

// SetChangeNote sets the "change_note" field.
func (_u *ArticleHistoryUpdateOne) SetChangeNote(v string) *ArticleHistoryUpdateOne {
	_u.mutation.SetChangeNote(v)
	return _u
}

// SetNillableChangeNote sets the "change_note" field if the given value is not nil.
func (_u *ArticleHistoryUpdateOne) SetNillableChangeNote(v *string) *ArticleHistoryUpdateOne {
	if v != nil {
		_u.SetChangeNote(*v)
	}
	return _u
}

// ClearChangeNote clears the value of the "change_note" field.
func (_u *ArticleHistoryUpdateOne) ClearChangeNote() *ArticleHistoryUpdateOne {
	_u.mutation.ClearChangeNote()
	return _u
}

// SetExtraData sets the "extra_data" field.
func (_u *ArticleHistoryUpdateOne) SetExtraData(v map[string]interface{}) *ArticleHistoryUpdateOne {
	_u.mutation.SetExtraData(v)
	return _u
}

// ClearExtraData clears the value of the "extra_data" field.
func (_u *ArticleHistoryUpdateOne) ClearExtraData() *ArticleHistoryUpdateOne {
	_u.mutation.ClearExtraData()
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *ArticleHistoryUpdateOne) SetArticle(v *Article) *ArticleHistoryUpdateOne {
	return _u.SetArticleID(v.ID)
}

// Mutation returns the ArticleHistoryMutation object of the builder.
func (_u *ArticleHistoryUpdateOne) Mutation() *ArticleHistoryMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *ArticleHistoryUpdateOne) ClearArticle() *ArticleHistoryUpdateOne {
	_u.mutation.ClearArticle()
	return _u
}

// Where appends a list predicates to the ArticleHistoryUpdate builder.
func (_u *ArticleHistoryUpdateOne) Where(ps ...predicate.ArticleHistory) *ArticleHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleHistoryUpdateOne) Select(field string, fields ...string) *ArticleHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ArticleHistory entity.
func (_u *ArticleHistoryUpdateOne) Save(ctx context.Context) (*ArticleHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleHistoryUpdateOne) SaveX(ctx context.Context) *ArticleHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := articlehistory.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := articlehistory.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WordCount(); ok {
		if err := articlehistory.WordCountValidator(v); err != nil {
			return &ValidationError{Name: "word_count", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.word_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeNote(); ok {
		if err := articlehistory.ChangeNoteValidator(v); err != nil {
			return &ValidationError{Name: "change_note", err: fmt.Errorf(`ent: validator failed for field "ArticleHistory.change_note": %w`, err)}
		}
	}
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleHistory.article"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ArticleHistoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticleHistoryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ArticleHistoryUpdateOne) sqlSave(ctx context.Context) (_node *ArticleHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articlehistory.Table, articlehistory.Columns, sqlgraph.NewFieldSpec(articlehistory.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ArticleHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articlehistory.FieldID)
		for _, f := range fields {
			if !articlehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != articlehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(articlehistory.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(articlehistory.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(articlehistory.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentMd(); ok {
		_spec.SetField(articlehistory.FieldContentMd, field.TypeString, value)
	}
	if _u.mutation.ContentMdCleared() {
		_spec.ClearField(articlehistory.FieldContentMd, field.TypeString)
	}
	if value, ok := _u.mutation.ContentHTML(); ok {
		_spec.SetField(articlehistory.FieldContentHTML, field.TypeString, value)
	}
	if _u.mutation.ContentHTMLCleared() {
		_spec.ClearField(articlehistory.FieldContentHTML, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(articlehistory.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(articlehistory.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.TopImgURL(); ok {
		_spec.SetField(articlehistory.FieldTopImgURL, field.TypeString, value)
	}
	if _u.mutation.TopImgURLCleared() {
		_spec.ClearField(articlehistory.FieldTopImgURL, field.TypeString)
	}
	if value, ok := _u.mutation.PrimaryColor(); ok {
		_spec.SetField(articlehistory.FieldPrimaryColor, field.TypeString, value)
	}
	if _u.mutation.PrimaryColorCleared() {
		_spec.ClearField(articlehistory.FieldPrimaryColor, field.TypeString)
	}
	if value, ok := _u.mutation.Summaries(); ok {
		_spec.SetField(articlehistory.FieldSummaries, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSummaries(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, articlehistory.FieldSummaries, value)
		})
	}
	if _u.mutation.SummariesCleared() {
		_spec.ClearField(articlehistory.FieldSummaries, field.TypeJSON)
	}
	if value, ok := _u.mutation.WordCount(); ok {
		_spec.SetField(articlehistory.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWordCount(); ok {
		_spec.AddField(articlehistory.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(articlehistory.FieldKeywords, field.TypeString, value)
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(articlehistory.FieldKeywords, field.TypeString)
	}
	if value, ok := _u.mutation.EditorID(); ok {
		_spec.SetField(articlehistory.FieldEditorID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedEditorID(); ok {
		_spec.AddField(articlehistory.FieldEditorID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.EditorNickname(); ok {
		_spec.SetField(articlehistory.FieldEditorNickname, field.TypeString, value)
	}
	if _u.mutation.EditorNicknameCleared() {
		_spec.ClearField(articlehistory.FieldEditorNickname, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeNote(); ok {
		_spec.SetField(articlehistory.FieldChangeNote, field.TypeString, value)
	}
	if _u.mutation.ChangeNoteCleared() {
		_spec.ClearField(articlehistory.FieldChangeNote, field.TypeString)
	}
	if value, ok := _u.mutation.ExtraData(); ok {
		_spec.SetField(articlehistory.FieldExtraData, field.TypeJSON, value)
	}
	if _u.mutation.ExtraDataCleared() {
		_spec.ClearField(articlehistory.FieldExtraData, field.TypeJSON)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articlehistory.ArticleTable,
			Columns: []string{articlehistory.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articlehistory.ArticleTable,
			Columns: []string{articlehistory.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ArticleHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articlehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
