// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/article"
	"github.com/anzhiyu-c/anheyu-app/ent/articlehistory"
)

// 文章历史版本表
type ArticleHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// 关联的文章ID
	ArticleID uint `json:"article_id,omitempty"`
	// 版本号，从1开始递增
	Version int `json:"version,omitempty"`
	// 文章标题
	Title string `json:"title,omitempty"`
	// Markdown内容
	ContentMd string `json:"content_md,omitempty"`
	// HTML内容
	ContentHTML string `json:"content_html,omitempty"`
	// 封面图URL
	CoverURL string `json:"cover_url,omitempty"`
	// 顶部大图URL
	TopImgURL string `json:"top_img_url,omitempty"`
	// 主色调
	PrimaryColor string `json:"primary_color,omitempty"`
	// 摘要列表
	Summaries []string `json:"summaries,omitempty"`
	// 字数
	WordCount int `json:"word_count,omitempty"`
	// 关键词
	Keywords string `json:"keywords,omitempty"`
	// 编辑者ID
	EditorID uint `json:"editor_id,omitempty"`
	// 编辑者昵称（冗余存储）
	EditorNickname string `json:"editor_nickname,omitempty"`
	// 变更说明
	ChangeNote string `json:"change_note,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 扩展数据（PRO版付费内容等）
	ExtraData map[string]interface{} `json:"extra_data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArticleHistoryQuery when eager-loading is set.
	Edges        ArticleHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArticleHistoryEdges holds the relations/edges for other nodes in the graph.
type ArticleHistoryEdges struct {
	// Article holds the value of the article edge.
	Article *Article `json:"article,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ArticleOrErr returns the Article value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArticleHistoryEdges) ArticleOrErr() (*Article, error) {
	if e.Article != nil {
		return e.Article, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: article.Label}
	}
	return nil, &NotLoadedError{edge: "article"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArticleHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case articlehistory.FieldSummaries, articlehistory.FieldExtraData:
			values[i] = new([]byte)
		case articlehistory.FieldID, articlehistory.FieldArticleID, articlehistory.FieldVersion, articlehistory.FieldWordCount, articlehistory.FieldEditorID:
			values[i] = new(sql.NullInt64)
		case articlehistory.FieldTitle, articlehistory.FieldContentMd, articlehistory.FieldContentHTML, articlehistory.FieldCoverURL, articlehistory.FieldTopImgURL, articlehistory.FieldPrimaryColor, articlehistory.FieldKeywords, articlehistory.FieldEditorNickname, articlehistory.FieldChangeNote:
			values[i] = new(sql.NullString)
		case articlehistory.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArticleHistory fields.
func (_m *ArticleHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case articlehistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case articlehistory.FieldArticleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field article_id", values[i])
			} else if value.Valid {
				_m.ArticleID = uint(value.Int64)
			}
		case articlehistory.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case articlehistory.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case articlehistory.FieldContentMd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_md", values[i])
			} else if value.Valid {
				_m.ContentMd = value.String
			}
		case articlehistory.FieldContentHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_html", values[i])
			} else if value.Valid {
				_m.ContentHTML = value.String
			}
		case articlehistory.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = value.String
			}
		case articlehistory.FieldTopImgURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field top_img_url", values[i])
			} else if value.Valid {
				_m.TopImgURL = value.String
			}
		case articlehistory.FieldPrimaryColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field primary_color", values[i])
			} else if value.Valid {
				_m.PrimaryColor = value.String
			}
		case articlehistory.FieldSummaries:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field summaries", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Summaries); err != nil {
					return fmt.Errorf("unmarshal field summaries: %w", err)
				}
			}
		case articlehistory.FieldWordCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field word_count", values[i])
			} else if value.Valid {
				_m.WordCount = int(value.Int64)
			}
		case articlehistory.FieldKeywords:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field keywords", values[i])
			} else if value.Valid {
				_m.Keywords = value.String
			}
		case articlehistory.FieldEditorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field editor_id", values[i])
			} else if value.Valid {
				_m.EditorID = uint(value.Int64)
			}
		case articlehistory.FieldEditorNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field editor_nickname", values[i])
			} else if value.Valid {
				_m.EditorNickname = value.String
			}
		case articlehistory.FieldChangeNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_note", values[i])
			} else if value.Valid {
				_m.ChangeNote = value.String
			}
		case articlehistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case articlehistory.FieldExtraData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraData); err != nil {
					return fmt.Errorf("unmarshal field extra_data: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArticleHistory.
// This includes values selected through modifiers, order, etc.
func (_m *ArticleHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArticle queries the "article" edge of the ArticleHistory entity.
func (_m *ArticleHistory) QueryArticle() *ArticleQuery {
	return NewArticleHistoryClient(_m.config).QueryArticle(_m)
}

// Update returns a builder for updating this ArticleHistory.
// Note that you need to call ArticleHistory.Unwrap() before calling this method if this ArticleHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ArticleHistory) Update() *ArticleHistoryUpdateOne {
	return NewArticleHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ArticleHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ArticleHistory) Unwrap() *ArticleHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArticleHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ArticleHistory) String() string {
	var builder strings.Builder
	builder.WriteString("ArticleHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("article_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ArticleID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content_md=")
	builder.WriteString(_m.ContentMd)
	builder.WriteString(", ")
	builder.WriteString("content_html=")
	builder.WriteString(_m.ContentHTML)
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(_m.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("top_img_url=")
	builder.WriteString(_m.TopImgURL)
	builder.WriteString(", ")
	builder.WriteString("primary_color=")
	builder.WriteString(_m.PrimaryColor)
	builder.WriteString(", ")
	builder.WriteString("summaries=")
	builder.WriteString(fmt.Sprintf("%v", _m.Summaries))
	builder.WriteString(", ")
	builder.WriteString("word_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.WordCount))
	builder.WriteString(", ")
	builder.WriteString("keywords=")
	builder.WriteString(_m.Keywords)
	builder.WriteString(", ")
	builder.WriteString("editor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EditorID))
	builder.WriteString(", ")
	builder.WriteString("editor_nickname=")
	builder.WriteString(_m.EditorNickname)
	builder.WriteString(", ")
	builder.WriteString("change_note=")
	builder.WriteString(_m.ChangeNote)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("extra_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraData))
	builder.WriteByte(')')
	return builder.String()
}

// ArticleHistories is a parsable slice of ArticleHistory.
type ArticleHistories []*ArticleHistory
