// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/article"
	"github.com/anzhiyu-c/anheyu-app/ent/docseries"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// DocSeriesQuery is the builder for querying DocSeries entities.
type DocSeriesQuery struct {
	config
	ctx          *QueryContext
	order        []docseries.OrderOption
	inters       []Interceptor
	predicates   []predicate.DocSeries
	withArticles *ArticleQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DocSeriesQuery builder.
func (_q *DocSeriesQuery) Where(ps ...predicate.DocSeries) *DocSeriesQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DocSeriesQuery) Limit(limit int) *DocSeriesQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DocSeriesQuery) Offset(offset int) *DocSeriesQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DocSeriesQuery) Unique(unique bool) *DocSeriesQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DocSeriesQuery) Order(o ...docseries.OrderOption) *DocSeriesQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryArticles chains the current query on the "articles" edge.
func (_q *DocSeriesQuery) QueryArticles() *ArticleQuery {
	query := (&ArticleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(docseries.Table, docseries.FieldID, selector),
			sqlgraph.To(article.Table, article.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, docseries.ArticlesTable, docseries.ArticlesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DocSeries entity from the query.
// Returns a *NotFoundError when no DocSeries was found.
func (_q *DocSeriesQuery) First(ctx context.Context) (*DocSeries, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{docseries.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DocSeriesQuery) FirstX(ctx context.Context) *DocSeries {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DocSeries ID from the query.
// Returns a *NotFoundError when no DocSeries ID was found.
func (_q *DocSeriesQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{docseries.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DocSeriesQuery) FirstIDX(ctx context.Context) uint {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DocSeries entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DocSeries entity is found.
// Returns a *NotFoundError when no DocSeries entities are found.
func (_q *DocSeriesQuery) Only(ctx context.Context) (*DocSeries, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{docseries.Label}
	default:
		return nil, &NotSingularError{docseries.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DocSeriesQuery) OnlyX(ctx context.Context) *DocSeries {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DocSeries ID in the query.
// Returns a *NotSingularError when more than one DocSeries ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DocSeriesQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{docseries.Label}
	default:
		err = &NotSingularError{docseries.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DocSeriesQuery) OnlyIDX(ctx context.Context) uint {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DocSeriesSlice.
func (_q *DocSeriesQuery) All(ctx context.Context) ([]*DocSeries, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DocSeries, *DocSeriesQuery]()
	return withInterceptors[[]*DocSeries](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DocSeriesQuery) AllX(ctx context.Context) []*DocSeries {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DocSeries IDs.
func (_q *DocSeriesQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(docseries.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DocSeriesQuery) IDsX(ctx context.Context) []uint {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DocSeriesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DocSeriesQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DocSeriesQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DocSeriesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DocSeriesQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DocSeriesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DocSeriesQuery) Clone() *DocSeriesQuery {
	if _q == nil {
		return nil
	}
	return &DocSeriesQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]docseries.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.DocSeries{}, _q.predicates...),
		withArticles: _q.withArticles.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithArticles tells the query-builder to eager-load the nodes that are connected to
// the "articles" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DocSeriesQuery) WithArticles(opts ...func(*ArticleQuery)) *DocSeriesQuery {
	query := (&ArticleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withArticles = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DocSeries.Query().
//		GroupBy(docseries.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DocSeriesQuery) GroupBy(field string, fields ...string) *DocSeriesGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DocSeriesGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = docseries.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DocSeries.Query().
//		Select(docseries.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *DocSeriesQuery) Select(fields ...string) *DocSeriesSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DocSeriesSelect{DocSeriesQuery: _q}
	sbuild.label = docseries.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DocSeriesSelect configured with the given aggregations.
func (_q *DocSeriesQuery) Aggregate(fns ...AggregateFunc) *DocSeriesSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DocSeriesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !docseries.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DocSeriesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DocSeries, error) {
	var (
		nodes       = []*DocSeries{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withArticles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DocSeries).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DocSeries{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withArticles; query != nil {
		if err := _q.loadArticles(ctx, query, nodes,
			func(n *DocSeries) { n.Edges.Articles = []*Article{} },
			func(n *DocSeries, e *Article) { n.Edges.Articles = append(n.Edges.Articles, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DocSeriesQuery) loadArticles(ctx context.Context, query *ArticleQuery, nodes []*DocSeries, init func(*DocSeries), assign func(*DocSeries, *Article)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint]*DocSeries)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(article.FieldDocSeriesID)
	}
	query.Where(predicate.Article(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(docseries.ArticlesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DocSeriesID
		if fk == nil {
			return fmt.Errorf(`foreign-key "doc_series_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "doc_series_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DocSeriesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DocSeriesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(docseries.Table, docseries.Columns, sqlgraph.NewFieldSpec(docseries.FieldID, field.TypeUint))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, docseries.FieldID)
		for i := range fields {
			if fields[i] != docseries.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DocSeriesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(docseries.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = docseries.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *DocSeriesQuery) Modify(modifiers ...func(s *sql.Selector)) *DocSeriesSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// DocSeriesGroupBy is the group-by builder for DocSeries entities.
type DocSeriesGroupBy struct {
	selector
	build *DocSeriesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DocSeriesGroupBy) Aggregate(fns ...AggregateFunc) *DocSeriesGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DocSeriesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DocSeriesQuery, *DocSeriesGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DocSeriesGroupBy) sqlScan(ctx context.Context, root *DocSeriesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DocSeriesSelect is the builder for selecting fields of DocSeries entities.
type DocSeriesSelect struct {
	*DocSeriesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DocSeriesSelect) Aggregate(fns ...AggregateFunc) *DocSeriesSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DocSeriesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DocSeriesQuery, *DocSeriesSelect](ctx, _s.DocSeriesQuery, _s, _s.inters, v)
}

func (_s *DocSeriesSelect) sqlScan(ctx context.Context, root *DocSeriesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *DocSeriesSelect) Modify(modifiers ...func(s *sql.Selector)) *DocSeriesSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
