// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/entity"
	"github.com/anzhiyu-c/anheyu-app/ent/file"
	"github.com/anzhiyu-c/anheyu-app/ent/fileentity"
)

// FileEntityCreate is the builder for creating a FileEntity entity.
type FileEntityCreate struct {
	config
	mutation *FileEntityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FileEntityCreate) SetDeletedAt(v time.Time) *FileEntityCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FileEntityCreate) SetNillableDeletedAt(v *time.Time) *FileEntityCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FileEntityCreate) SetCreatedAt(v time.Time) *FileEntityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FileEntityCreate) SetNillableCreatedAt(v *time.Time) *FileEntityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FileEntityCreate) SetUpdatedAt(v time.Time) *FileEntityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FileEntityCreate) SetNillableUpdatedAt(v *time.Time) *FileEntityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *FileEntityCreate) SetFileID(v uint) *FileEntityCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *FileEntityCreate) SetEntityID(v uint) *FileEntityCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *FileEntityCreate) SetVersion(v string) *FileEntityCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *FileEntityCreate) SetNillableVersion(v *string) *FileEntityCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetIsCurrent sets the "is_current" field.
func (_c *FileEntityCreate) SetIsCurrent(v bool) *FileEntityCreate {
	_c.mutation.SetIsCurrent(v)
	return _c
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_c *FileEntityCreate) SetNillableIsCurrent(v *bool) *FileEntityCreate {
	if v != nil {
		_c.SetIsCurrent(*v)
	}
	return _c
}

// SetUploadedByUserID sets the "uploaded_by_user_id" field.
func (_c *FileEntityCreate) SetUploadedByUserID(v uint64) *FileEntityCreate {
	_c.mutation.SetUploadedByUserID(v)
	return _c
}

// SetNillableUploadedByUserID sets the "uploaded_by_user_id" field if the given value is not nil.
func (_c *FileEntityCreate) SetNillableUploadedByUserID(v *uint64) *FileEntityCreate {
	if v != nil {
		_c.SetUploadedByUserID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FileEntityCreate) SetID(v uint) *FileEntityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetFile sets the "file" edge to the File entity.
func (_c *FileEntityCreate) SetFile(v *File) *FileEntityCreate {
	return _c.SetFileID(v.ID)
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_c *FileEntityCreate) SetEntity(v *Entity) *FileEntityCreate {
	return _c.SetEntityID(v.ID)
}

// Mutation returns the FileEntityMutation object of the builder.
func (_c *FileEntityCreate) Mutation() *FileEntityMutation {
	return _c.mutation
}

// Save creates the FileEntity in the database.
func (_c *FileEntityCreate) Save(ctx context.Context) (*FileEntity, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileEntityCreate) SaveX(ctx context.Context) *FileEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileEntityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileEntityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileEntityCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if fileentity.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized fileentity.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := fileentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if fileentity.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized fileentity.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := fileentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsCurrent(); !ok {
		v := fileentity.DefaultIsCurrent
		_c.mutation.SetIsCurrent(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileEntityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FileEntity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FileEntity.updated_at"`)}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "FileEntity.file_id"`)}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "FileEntity.entity_id"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := fileentity.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "FileEntity.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsCurrent(); !ok {
		return &ValidationError{Name: "is_current", err: errors.New(`ent: missing required field "FileEntity.is_current"`)}
	}
	if len(_c.mutation.FileIDs()) == 0 {
		return &ValidationError{Name: "file", err: errors.New(`ent: missing required edge "FileEntity.file"`)}
	}
	if len(_c.mutation.EntityIDs()) == 0 {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required edge "FileEntity.entity"`)}
	}
	return nil
}

func (_c *FileEntityCreate) sqlSave(ctx context.Context) (*FileEntity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileEntityCreate) createSpec() (*FileEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &FileEntity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fileentity.Table, sqlgraph.NewFieldSpec(fileentity.FieldID, field.TypeUint))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(fileentity.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fileentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fileentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(fileentity.FieldVersion, field.TypeString, value)
		_node.Version = &value
	}
	if value, ok := _c.mutation.IsCurrent(); ok {
		_spec.SetField(fileentity.FieldIsCurrent, field.TypeBool, value)
		_node.IsCurrent = value
	}
	if value, ok := _c.mutation.UploadedByUserID(); ok {
		_spec.SetField(fileentity.FieldUploadedByUserID, field.TypeUint64, value)
		_node.UploadedByUserID = &value
	}
	if nodes := _c.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileentity.FileTable,
			Columns: []string{fileentity.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileentity.EntityTable,
			Columns: []string{fileentity.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FileEntity.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileEntityUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FileEntityCreate) OnConflict(opts ...sql.ConflictOption) *FileEntityUpsertOne {
	_c.conflict = opts
	return &FileEntityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FileEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileEntityCreate) OnConflictColumns(columns ...string) *FileEntityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileEntityUpsertOne{
		create: _c,
	}
}

type (
	// FileEntityUpsertOne is the builder for "upsert"-ing
	//  one FileEntity node.
	FileEntityUpsertOne struct {
		create *FileEntityCreate
	}

	// FileEntityUpsert is the "OnConflict" setter.
	FileEntityUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *FileEntityUpsert) SetDeletedAt(v time.Time) *FileEntityUpsert {
	u.Set(fileentity.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FileEntityUpsert) UpdateDeletedAt() *FileEntityUpsert {
	u.SetExcluded(fileentity.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FileEntityUpsert) ClearDeletedAt() *FileEntityUpsert {
	u.SetNull(fileentity.FieldDeletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FileEntityUpsert) SetUpdatedAt(v time.Time) *FileEntityUpsert {
	u.Set(fileentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileEntityUpsert) UpdateUpdatedAt() *FileEntityUpsert {
	u.SetExcluded(fileentity.FieldUpdatedAt)
	return u
}

// SetFileID sets the "file_id" field.
func (u *FileEntityUpsert) SetFileID(v uint) *FileEntityUpsert {
	u.Set(fileentity.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FileEntityUpsert) UpdateFileID() *FileEntityUpsert {
	u.SetExcluded(fileentity.FieldFileID)
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *FileEntityUpsert) SetEntityID(v uint) *FileEntityUpsert {
	u.Set(fileentity.FieldEntityID, v)
	return u
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *FileEntityUpsert) UpdateEntityID() *FileEntityUpsert {
	u.SetExcluded(fileentity.FieldEntityID)
	return u
}

// SetVersion sets the "version" field.
func (u *FileEntityUpsert) SetVersion(v string) *FileEntityUpsert {
	u.Set(fileentity.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *FileEntityUpsert) UpdateVersion() *FileEntityUpsert {
	u.SetExcluded(fileentity.FieldVersion)
	return u
}

// ClearVersion clears the value of the "version" field.
func (u *FileEntityUpsert) ClearVersion() *FileEntityUpsert {
	u.SetNull(fileentity.FieldVersion)
	return u
}

// SetIsCurrent sets the "is_current" field.
func (u *FileEntityUpsert) SetIsCurrent(v bool) *FileEntityUpsert {
	u.Set(fileentity.FieldIsCurrent, v)
	return u
}

// UpdateIsCurrent sets the "is_current" field to the value that was provided on create.
func (u *FileEntityUpsert) UpdateIsCurrent() *FileEntityUpsert {
	u.SetExcluded(fileentity.FieldIsCurrent)
	return u
}

// SetUploadedByUserID sets the "uploaded_by_user_id" field.
func (u *FileEntityUpsert) SetUploadedByUserID(v uint64) *FileEntityUpsert {
	u.Set(fileentity.FieldUploadedByUserID, v)
	return u
}

// UpdateUploadedByUserID sets the "uploaded_by_user_id" field to the value that was provided on create.
func (u *FileEntityUpsert) UpdateUploadedByUserID() *FileEntityUpsert {
	u.SetExcluded(fileentity.FieldUploadedByUserID)
	return u
}

// AddUploadedByUserID adds v to the "uploaded_by_user_id" field.
func (u *FileEntityUpsert) AddUploadedByUserID(v uint64) *FileEntityUpsert {
	u.Add(fileentity.FieldUploadedByUserID, v)
	return u
}

// ClearUploadedByUserID clears the value of the "uploaded_by_user_id" field.
func (u *FileEntityUpsert) ClearUploadedByUserID() *FileEntityUpsert {
	u.SetNull(fileentity.FieldUploadedByUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.FileEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(fileentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FileEntityUpsertOne) UpdateNewValues() *FileEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(fileentity.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(fileentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FileEntity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FileEntityUpsertOne) Ignore() *FileEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileEntityUpsertOne) DoNothing() *FileEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileEntityCreate.OnConflict
// documentation for more info.
func (u *FileEntityUpsertOne) Update(set func(*FileEntityUpsert)) *FileEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FileEntityUpsertOne) SetDeletedAt(v time.Time) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FileEntityUpsertOne) UpdateDeletedAt() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FileEntityUpsertOne) ClearDeletedAt() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FileEntityUpsertOne) SetUpdatedAt(v time.Time) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileEntityUpsertOne) UpdateUpdatedAt() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFileID sets the "file_id" field.
func (u *FileEntityUpsertOne) SetFileID(v uint) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FileEntityUpsertOne) UpdateFileID() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateFileID()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *FileEntityUpsertOne) SetEntityID(v uint) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *FileEntityUpsertOne) UpdateEntityID() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateEntityID()
	})
}

// SetVersion sets the "version" field.
func (u *FileEntityUpsertOne) SetVersion(v string) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *FileEntityUpsertOne) UpdateVersion() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateVersion()
	})
}

// ClearVersion clears the value of the "version" field.
func (u *FileEntityUpsertOne) ClearVersion() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.ClearVersion()
	})
}

// SetIsCurrent sets the "is_current" field.
func (u *FileEntityUpsertOne) SetIsCurrent(v bool) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetIsCurrent(v)
	})
}

// UpdateIsCurrent sets the "is_current" field to the value that was provided on create.
func (u *FileEntityUpsertOne) UpdateIsCurrent() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateIsCurrent()
	})
}

// SetUploadedByUserID sets the "uploaded_by_user_id" field.
func (u *FileEntityUpsertOne) SetUploadedByUserID(v uint64) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetUploadedByUserID(v)
	})
}

// AddUploadedByUserID adds v to the "uploaded_by_user_id" field.
func (u *FileEntityUpsertOne) AddUploadedByUserID(v uint64) *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.AddUploadedByUserID(v)
	})
}

// UpdateUploadedByUserID sets the "uploaded_by_user_id" field to the value that was provided on create.
func (u *FileEntityUpsertOne) UpdateUploadedByUserID() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateUploadedByUserID()
	})
}

// ClearUploadedByUserID clears the value of the "uploaded_by_user_id" field.
func (u *FileEntityUpsertOne) ClearUploadedByUserID() *FileEntityUpsertOne {
	return u.Update(func(s *FileEntityUpsert) {
		s.ClearUploadedByUserID()
	})
}

// Exec executes the query.
func (u *FileEntityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileEntityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileEntityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FileEntityUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FileEntityUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FileEntityCreateBulk is the builder for creating many FileEntity entities in bulk.
type FileEntityCreateBulk struct {
	config
	err      error
	builders []*FileEntityCreate
	conflict []sql.ConflictOption
}

// Save creates the FileEntity entities in the database.
func (_c *FileEntityCreateBulk) Save(ctx context.Context) ([]*FileEntity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileEntity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileEntityCreateBulk) SaveX(ctx context.Context) []*FileEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileEntityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FileEntity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileEntityUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FileEntityCreateBulk) OnConflict(opts ...sql.ConflictOption) *FileEntityUpsertBulk {
	_c.conflict = opts
	return &FileEntityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FileEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileEntityCreateBulk) OnConflictColumns(columns ...string) *FileEntityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileEntityUpsertBulk{
		create: _c,
	}
}

// FileEntityUpsertBulk is the builder for "upsert"-ing
// a bulk of FileEntity nodes.
type FileEntityUpsertBulk struct {
	create *FileEntityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FileEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(fileentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FileEntityUpsertBulk) UpdateNewValues() *FileEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(fileentity.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(fileentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FileEntity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FileEntityUpsertBulk) Ignore() *FileEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileEntityUpsertBulk) DoNothing() *FileEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileEntityCreateBulk.OnConflict
// documentation for more info.
func (u *FileEntityUpsertBulk) Update(set func(*FileEntityUpsert)) *FileEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FileEntityUpsertBulk) SetDeletedAt(v time.Time) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FileEntityUpsertBulk) UpdateDeletedAt() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FileEntityUpsertBulk) ClearDeletedAt() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FileEntityUpsertBulk) SetUpdatedAt(v time.Time) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileEntityUpsertBulk) UpdateUpdatedAt() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFileID sets the "file_id" field.
func (u *FileEntityUpsertBulk) SetFileID(v uint) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FileEntityUpsertBulk) UpdateFileID() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateFileID()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *FileEntityUpsertBulk) SetEntityID(v uint) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *FileEntityUpsertBulk) UpdateEntityID() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateEntityID()
	})
}

// SetVersion sets the "version" field.
func (u *FileEntityUpsertBulk) SetVersion(v string) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *FileEntityUpsertBulk) UpdateVersion() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateVersion()
	})
}

// ClearVersion clears the value of the "version" field.
func (u *FileEntityUpsertBulk) ClearVersion() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.ClearVersion()
	})
}

// SetIsCurrent sets the "is_current" field.
func (u *FileEntityUpsertBulk) SetIsCurrent(v bool) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetIsCurrent(v)
	})
}

// UpdateIsCurrent sets the "is_current" field to the value that was provided on create.
func (u *FileEntityUpsertBulk) UpdateIsCurrent() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateIsCurrent()
	})
}

// SetUploadedByUserID sets the "uploaded_by_user_id" field.
func (u *FileEntityUpsertBulk) SetUploadedByUserID(v uint64) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.SetUploadedByUserID(v)
	})
}

// AddUploadedByUserID adds v to the "uploaded_by_user_id" field.
func (u *FileEntityUpsertBulk) AddUploadedByUserID(v uint64) *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.AddUploadedByUserID(v)
	})
}

// UpdateUploadedByUserID sets the "uploaded_by_user_id" field to the value that was provided on create.
func (u *FileEntityUpsertBulk) UpdateUploadedByUserID() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.UpdateUploadedByUserID()
	})
}

// ClearUploadedByUserID clears the value of the "uploaded_by_user_id" field.
func (u *FileEntityUpsertBulk) ClearUploadedByUserID() *FileEntityUpsertBulk {
	return u.Update(func(s *FileEntityUpsert) {
		s.ClearUploadedByUserID()
	})
}

// Exec executes the query.
func (u *FileEntityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FileEntityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileEntityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileEntityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
